// Warning: generated file; your changes could be lost when a new file is generated.
#r @"..\..\..\packages\encog-dotnet-core\lib\net35\encog-core-cs.dll"
#r @"..\..\..\packages\ExtCore\lib\net40\ExtCore.dll"
#r @"..\..\..\packages\FsControl\lib\net40\FsControl.Core.dll"
#r @"..\..\..\packages\FSharp.Charting\lib\net40\FSharp.Charting.dll"
#r @"..\..\..\packages\FSharp.Data\lib\net40\FSharp.Data.dll"
#r @"..\..\..\packages\FSharpPlus\lib\net40\FSharpPlus.dll"
#r @"..\..\..\packages\FSharpx\lib\FSharpx.dll"
#r @"..\..\..\packages\FSharpx.Async\lib\net40\FSharpx.Async.dll"
#r @"..\..\..\packages\FSharpx.Collections\lib\net40\FSharpx.Collections.dll"
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Numerics.dll"
#r @"System.Xml.Linq.dll"